version: '3.9'

services:
  db:
    image: mysql:8.3.0
    ports:
      - '47964:3306'
    environment:
      MYSQL_ROOT_PASSWORD: $X_ROOT_PWD
      MYSQL_DATABASE: $X_BDD
      MYSQL_USER: $X_BDD_USER
      MYSQL_PASSWORD: $X_BDD_PWD
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - '48152:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: $X_ROOT_PWD
      MYSQL_USER: $X_BDD_USER
      MYSQL_PASSWORD: $X_BDD_PWD
volumes:
  db-data: