version: '3.9'

services:
  db:
    image: mysql:8.3.0
    ports:
      - '47964:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: bdd1234
      MYSQL_USER: user1234
      MYSQL_PASSWORD: 1234
    volumes:
      - db-data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin:5.2.1-apache
    ports:
      - '48152:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_USER: user1234
      MYSQL_PASSWORD: 1234
    volumes:
      - ./config.inc.php:/etc/phpmyadmin/config.inc.php:ro
volumes:
  db-data: