version: 2.1

orbs:
  docker: circleci/docker@2.7.0

jobs:
  push-docker-compose-file:
    executor:
      name: docker/docker
      tag: "3.9"
    steps:
      - checkout
      - run:
          name: Pushing Docker compose file
          command: |
            ls -la
            echo "Starting pushing docker image & config to VPS"
            scp -oStrictHostKeyChecking=no docker-compose.yml $SSHUSER@$SSHHOST:~/
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'mkdir -p x-bdd'
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'mv docker-compose.yml ~/x-bdd'
            echo "Docker compose file pushed to VPS"
  docker-compose-up:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - run:
          name: Docker compose down
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'docker compose down -f /x-bdd/docker-compose.yml'
      - run:
          name: Docker compose up
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'X_ROOT_PWD=$X_ROOT_PWD X_BDD=$X_BDD X_BDD_USER=$X_BDD_USER X_BDD_PWD=$X_BDD_PWD docker compose up -d -f /x-bdd/docker-compose.yml'
  
workflows:
  build-and-deploy:
    jobs:
      - push-docker-compose-file
      - docker-compose-up:
          requires:
            - push-docker-compose-file
      
      