version: 2.1

orbs:
  docker: circleci/docker@2.7.0

jobs:
  push-docker-compose-file:
    executor:
      name: docker/docker
      tag: "3.9"
    steps:
      - checkout
      - run:
          name: Generate .env file
          command: |
            echo "X_ROOT_PWD=$X_ROOT_PWD" > .env
            echo "X_BDD=$X_BDD" >> .env
            echo "X_BDD_USER=$X_BDD_USER" >> .env
            echo "X_BDD_PWD=$X_BDD_PWD" >> .env
      - run:
          name: Pushing Docker compose file
          command: |
            ls -la
            echo "Starting pushing docker image & config to VPS"
            scp -oStrictHostKeyChecking=no docker-compose.yml $SSHUSER@$SSHHOST:~/
            scp -oStrictHostKeyChecking=no .env $SSHUSER@$SSHHOST:~/
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'mkdir -p x-bdd'
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'mv docker-compose.yml ~/x-bdd'
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'mv .env ~/x-bdd'
            echo "Docker compose files pushed to VPS"
  docker-compose-up:
    executor:
      name: docker/docker
      tag: "3.6"
    steps:
      - run:
          name: Docker compose down
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'docker compose -f ~/x-bdd/docker-compose.yml down'
      - run:
          name: Docker compose up
          command: |
            ssh -oStrictHostKeyChecking=no $SSHUSER@$SSHHOST 'X_ROOT_PWD=$X_ROOT_PWD X_BDD=$X_BDD X_BDD_USER=$X_BDD_USER X_BDD_PWD=$X_BDD_PWD docker compose -f ~/x-bdd/docker-compose.yml up -d'
  
workflows:
  build-and-deploy:
    jobs:
      - push-docker-compose-file
      - docker-compose-up:
          requires:
            - push-docker-compose-file
      
      