version: 2.1

orbs:
  docker: circleci/docker@2.7.0

jobs:
  push-docker-compose-file:
    executor:
      name: docker/docker
      tag: "3.9"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Pushing Docker compose file
          command: |
            ls -la
            echo "Starting pushing docker image & config to VPS"
            scp -oStrictHostKeyChecking=no docker-compose.yml $SSHUSER@$SSHHOST:~/x-bdd
            echo "Docker compose file pushed to VPS"
  
workflows:
  build-and-deploy:
    jobs:
      - push-docker-compose-file
      
      